# Generated by Django 4.1.2 on 2022-12-14 02:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentarist', models.TextField(max_length=20)),
                ('text_commentary', models.TextField(max_length=400)),
                ('date_commentary', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag1', models.CharField(choices=[('TR', 'Travel'), ('AR', 'Argentina'), ('CL', 'Chile'), ('CY', 'Cuyo'), ('PAT', 'Patagonia'), ('MDP', 'Costa Atlántica'), ('BSAS', 'Buenos Aires'), ('COB', 'Centro'), ('PN', 'Parques'), ('LG', 'Lagos'), ('RN', 'Rutas'), ('MNT', 'Montañas'), ('ID', 'Ideas'), ('TIP', 'Rata-tips')], max_length=4)),
                ('tag2', models.CharField(choices=[('TR', 'Travel'), ('AR', 'Argentina'), ('CL', 'Chile'), ('CY', 'Cuyo'), ('PAT', 'Patagonia'), ('MDP', 'Costa Atlántica'), ('BSAS', 'Buenos Aires'), ('COB', 'Centro'), ('PN', 'Parques'), ('LG', 'Lagos'), ('RN', 'Rutas'), ('MNT', 'Montañas'), ('ID', 'Ideas'), ('TIP', 'Rata-tips')], max_length=4)),
                ('url', models.CharField(max_length=50)),
                ('title', models.TextField(max_length=50)),
                ('subtitle', models.TextField(max_length=80)),
                ('image', models.CharField(max_length=50)),
                ('image_alt', models.CharField(max_length=50)),
                ('image_title', models.CharField(max_length=50)),
                ('readmore_avaliable', models.BooleanField()),
                ('description', models.TextField(max_length=300)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('image_portada', models.ImageField(upload_to='portadas_post')),
                ('image_contenido', models.ImageField(blank=True, null=True, upload_to='contenido_post')),
            ],
        ),
    ]
