# Generated by Django 4.1.2 on 2022-12-14 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0002_remove_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_alt',
            new_name='image_contenido_alt',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image_title',
            new_name='image_contenido_title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
        migrations.AddField(
            model_name='post',
            name='image_portada_alt',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='image_portada_title',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
