# Generated by Django 4.1.2 on 2022-12-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0003_rename_image_alt_post_image_contenido_alt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_content',
            field=models.TextField(default='', max_length=7000),
            preserve_default=False,
        ),
    ]
