# Generated by Django 4.1.2 on 2022-12-14 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0004_post_text_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='related_post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='contenido.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='image_contenido_alt',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_contenido_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(max_length=50, unique=True),
        ),
    ]
