# Generated by Django 4.1.2 on 2022-12-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0007_remove_post_readmore_avaliable'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_contenido2',
            field=models.ImageField(blank=True, null=True, upload_to='contenido_post'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_contenido2_alt',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='image_contenido2_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='image_contenido3',
            field=models.ImageField(blank=True, null=True, upload_to='contenido_post'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_contenido3_alt',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='image_contenido3_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='image_contenido4',
            field=models.ImageField(blank=True, null=True, upload_to='contenido_post'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_contenido4_alt',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='image_contenido4_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
