# Generated by Django 4.1.2 on 2022-12-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0008_post_image_contenido2_post_image_contenido2_alt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_contenido2_paragraph',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='image_contenido3_paragraph',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='image_contenido4_paragraph',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='image_contenido_paragraph',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
