# Generated by Django 4.1.2 on 2022-12-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0009_post_image_contenido2_paragraph_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_contenido2_paragraph',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_contenido3_paragraph',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_contenido4_paragraph',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_contenido_paragraph',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
